// react_web/src/pages/login.js
import React, { Component } from 'react';
import axios from 'axios';

const API_LOGIN = "http://localhost:8000/server/login";

class Login extends Component {
  constructor(props){
    super(props);
    this.state = {
      correo: '',
      clave: '',
    };
  }

  changeHandler = (e) => {
    this.setState({ [e.target.name]: e.target.value })
  }

  loginAccess = e => {
    e.preventDefault()
    if (this.state.correo === "" || this.state.clave === "") {
      alert("Complete todos los datos para continuar...");
    } else {
      axios.post(API_LOGIN, this.state)
      .then(response => {
        if ( response.data.mensaje === "found" ) {
          window.location.assign("http://localhost:3000/register");
        }
      })
      .catch(error => {
        alert("Datos Incorrectos")
      })
    }
  };

  render() {
    const { correo, clave } = this.state
    return (
      <div className="bg-teal-200 h-screen font-sans">
        <div className="container mx-auto h-full flex justify-center items-center">
        <div className="w-1/3">
            <h1 className="font-hairline mb-6 text-center text-2xl">Bienvenido!</h1>
            <div className="border-teal p-8 border-t-12 bg-white mb-6 rounded-lg shadow-lg">
              <form className="px-8 pt-6 pb-8 mb-4 bg-white rounded" onSubmit={ this.loginAccess }>
                <div className="mb-4">
                  <label className="font-bold text-gray-700 block mb-2">Correo Institucional</label>
                  <input className="block appearance-none w-full bg-white border border-grey-light hover:border-grey px-2 py-2 rounded shadow"
                  type="text"
                  placeholder="correo@gmail.com"
                  name="correo"
                  value={ correo }
                  onChange={ this.changeHandler }
                  autoComplete="off"
                  />
                </div>

                <div className="mb-4">
                  <label className="font-bold text-gray-700 block mb-2">Contraseña</label>
                  <input className="block appearance-none w-full bg-white border border-grey-light hover:border-grey px-2 py-2 rounded shadow"
                  type="password"
                  placeholder="**************"
                  name="clave"
                  value={ clave }
                  onChange={ this.changeHandler } 
                  securetextentry="true"
                  />
                </div>

                <div className="flex items-center justify-between">
                  <button type="submit" className="bg-teal-600 hover:bg-teal-700 focus:outline-none focus:shadow-outline text-white font-bold py-2 px-4 rounded">
                    Ingresar
                  </button>
                  <a href="http://localhost:3000/register" className="bg-blue-600 hover:bg-blue-700 focus:outline-none focus:shadow-outline text-white font-bold py-2 px-4 rounded">
                    Registrarse
                  </a>
                </div>  
              </form>
            </div>
          </div>
        </div>
      </div>
    )
  }
}

export default Login;

// vistas/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { environment } from 'src/environments/environment';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  constructor(private http: HttpClient) { }

  ngOnInit(): void {
    this.login();
  }

  respuesta: any[]

  login = () => {
    const register = {
      datos: [{
        persona_email: idcliente,
        persona_clave: idestado
    }]}

    this.http.post(environment.API_URL, register)
      .subscribe(data => {
        alert(data)
      })
      window.location.reload()
  }
}

<div class="container mx-auto h-full flex justify-center items-center">
    <div class="w-1/3">
        <h1 class="font-medium mb-6 text-center text-3xl">Matriz Estadística</h1>
        <div class="border-teal p-8 border-t-12 bg-white mb-6 rounded-lg shadow-lg">
            <div class="mb-4">
                <label  class="font-bold text-grey-darker block mb-2">Correo Electrónico</label>
                <input #persona_email type="email"
                    class="block appearance-none w-full bg-white border border-grey-light hover:border-grey px-2 py-2 rounded shadow"
                    placeholder="Correo electrónico"/>
            </div>

            <div class="mb-4">
                <label class="font-bold text-grey-darker block mb-2">Contraseña</label>
                <input  #persona_clave type="text"
                    class="block appearance-none w-full bg-white border border-grey-light hover:border-grey px-2 py-2 rounded shadow"
                    placeholder="Contraseña"/>
            </div>

            <div class="flex items-center justify-between">
                <a ><button
                      (click)="login()"  class="bg-blue-500 hover:bg-teal text-white font-bold py-2 px-4 rounded">
                        Ingresar
                    </button></a>
            </div>
        </div>
    </div>
</div>
